# Generated by Django 4.1.1 on 2022-09-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='fundation',
            new_name='foundation',
        ),
    ]
